### ISSUE TITLE
Bad advice for configuring StyleCop

### ISSUE THREAD

**Issue by megamindbrian** [StyleCop/StyleCop#130]
Somehow there are projects with this line:
Exists('..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets')

Not sure how it got there or if StyleCop is adding it or some instructions on the internet tell people to add it but it prevents projects from building.  This is highly abusive of that feature.  Some superfluous plugin should not be allowed to prevent a build.

**Comment by csdahlberg** [comment]
The `StyleCop.MSBuild.Targets` file is included in the project file by installing the `StyleCop.MSBuild` NuGet package. It is the correct way to have a NuGet package customize the build process, as described in [Microsoft's documentation](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package). It is required in order to run StyleCop analysis as part of the build, and is neither bad advice nor abusive.

If you don't want StyleCop to run as part of the build, don't install the `StyleCop.MSBuild` package.

**Comment by megamindbrian** [comment]
Is there some way to make it not cause errors on Release build?  This is
how your package is being used:

https://github.com/zabirauf/icsharp/wiki/Installation

[image: Inline image 1]

Maybe it isn't being updated with the new version number in the csproj
files?

I'm going to submit a PR that doesn't include it in the project.  NuGet is
not very smart with this stuff, I've found.

**Comment by megamindbrian** [comment]
Of course it doesn't remove this line when I uninstall StyleCop.MsBuild it:
```
    <Error
Condition="!Exists('..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets')"
Text="$([System.String]::Format('$(ErrorText)',
'..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets'))"
/>

```

**Comment by csdahlberg** [comment]
I checked out the iCSharp repo, and saw the same error when trying to follow those instructions. There are multiple problems with how NuGet packages are being used in that repo, but I was able to quickly get `.\iCSharp.sln` building by first restoring packages for `.\Engine\ScriptCs.sln`.

On Windows you can do that by right-clicking on on the ScriptCs solution in Solution Explorer and choosing the option to restore NuGet packages, or on the command line you can run `.nuget\NuGet.exe restore Engine\ScriptCs.sln` from the root of the iCSharp repo.

On Linux/Mac it looks like you can restore packages and build by just running `build_brew.sh` in the root of the repo.

**Comment by megamindbrian** [comment]
Lmftfy, there are many problems with nuget. Thanks for the try, I submitted
a PR. Why wouldn't reinstalling the .50 version update the version in the
csproj files?
