### ISSUE TITLE
SA1650 - SpellCheckCorrectly problem with language

### ISSUE THREAD

**Issue by marspion** [StyleCop/StyleCop#160]
Hello,

Im not sure it is issue with StyleCop or with my PC configuration.
I have a problem with SA1650 rule. I reinstalled system on my PC (before reinstallation everything worked properly) and after that my StyleCop don't check documentation headers by correctly check (Polish language). I tried to reinstall StyleCop, copy settings from other programmers but it didn't help.

Do you know anything about this problem?

**Comment by Emeka-NMC** [comment]
Are the following true?
- you are on a 64bit version of windows.
- you don't have a 32bit version of office installed.

If so, it might be due to how stylecop code handles language spellers:
1 - assumes 64bit (and thus only checks 32bit version of office for MS-Office speller DLL.)
2 - attempts to fallback to version it comes with (however it specifies the wrong path to itself, and thus can't find it's own speller DLL).

**Comment by marspion** [comment]
Hello, thank you for your answer. Yes that's following are true. I using Windows 10 (64bit) and Office (64bit).
