### ISSUE TITLE
Support ReSharper 9.1

### ISSUE THREAD

**Issue by meh-uk** [StyleCop/StyleCop#2]
I know this one is obvious but we should support the latest ReSharper.

**Comment by citizenmatt** [comment]
There is already a port for 9.1 (and 9.0): https://resharper-plugins.jetbrains.com/packages/ReSharper.StyleCop/4.7.51-beta1

You need to enable pre-release extensions in ReSharper → Options → Extension Manager before you'll see it in the Extension Manager.

This fork has been created because a) the author of that 9.x port (@kubiix) hasn't made it open source, and isn't replying to attempts to contact, and b) so that we can release a version that isn't pre-release, to make it much easier to find.

**Comment by philippdolder** [comment]
@citizenmatt either I'm blind or sth, but where's the latest code for the plugin? the latest commit I can see in this repository is from `Andy Reeves authored on Mar 31, 2014`

**Comment by citizenmatt** [comment]
This repo doesn't have the code for that plugin. As I said above, the author of the current port available on the gallery hasn't made the code open source. Currently, no work has happened with this repo.

**Comment by meh-uk** [comment]
I'd have thought the first step would be to create a shared base library for all the stuff that's the same between the different ReSharper projects as there's a lot of duplication.

**Comment by citizenmatt** [comment]
Closing this, in favour of #9 - Support ReSharper 9.2. Once 9.2 is supported, I don't see the need for 9.1, but can back port if there's demand.
