### ISSUE TITLE
Confusion over settings

### ISSUE THREAD

**Issue by andyste1** [StyleCop/StyleCop#21]
I'm still a bit confused as to how StyleCop, R# and your plugin co-exist, especially regarding the settings. We have StyleCop 4.7 installed, and up until today have always had a settings.stylecop file in each of our TFS "branch" folders (not the solution folder, but the one above this). I've never been happy with all these settings files, so today I deleted them all, after first copying our custom settings into the "global" settings.stylecop file (in C:\Program Files (x86)\StyleCop 4.7\).

Now, if I run StyleCop manually (right-click solution explorer -> "Run StyleCop (Rescan All)")  everything is still good, and no violations are reported. However the VS editor is now showing blue squiggles everywhere. Why has this started happening - does your plugin ignore the "global" settings file in the StyleCop install folder and only walk the tree that the solution is in? 

Also, looking at my R# layers, all the StyleCop "inspection severity" items are set to "Warning", so I don't understand how things could have ever worked, even before today's changes. Your extension is the lowest layer in the list, so how does it override the StyleCop inspection severity settings in the higher layers?

Thanks in advance.

**EDIT**: sure enough it works if I put the settings file higher up in the folder hierarchy. I believe your plugin doesn't need StyleCop to be installed, so I guess it is not obliged to look in the StyleCop install folder for a settings file? I'm still curious as regards to my last paragraph...!

**Comment by citizenmatt** [comment]
Yes, the StyleCop ReSharper plugin doesn't require StyleCop to be installed, and as such, doesn't look in Program Files for the settings defaults. Instead, the defaults are shipped as part of the ReSharper extension. You would have to make your changes there, but I wouldn't advise it, as they will be overwritten by any new versions of the plugin. You're better off maintaining a copy at the root of your solution.

So this likely explains why you're seeing differences - if you've changed the global settings, the command line from the install will use different settings to the plugin (another good reason to keep your settings with the solution - both tools will be in sync).

I think looking at the severity level is a bit of a red herring. The command line is showing no warnings because you've edited the defaults, and disabled rules. The ReSharper plugin is showing warnings because you've deleted the per solution settings, and ReSharper doesn't look at the separate program install location (because it doesn't require the program to be installed). It would have worked before, because the plugin was picking up the settings files you've deleted.

The inspection severity levels are only used when the issues are reported, and don't control whether the inspections are disabled or not. So, you can disable the inspections in the style cop settings, but the inspection severity will still show "warning". But the analysis won't run the inspections.

I'm going to close the issue now, feel free to reopen if this doesn't make sense.
