### ISSUE TITLE
SA1001 Code Cleanup invalid spacing in object initialization

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#25]
Example:
```
                    order.Lines.Add(
                        new OrderLine
                            {
                                Name = shippingLineName,
                                IsProduct = false,
                                Price = shippingAmount,
                                Quantity = 1M,'_' <-excessive space here 
                                Tax = shippingTax,
                                TotalPerLine = shippingAmount,
                            });
```

**Comment by dfyx** [comment]
I guess you should wrap your code in \``` so the spacing is visible.

**Comment by citizenmatt** [comment]
Yeah, could you provide more details, please? I don't know what the problem is here.

**Comment by dmitriyse** [comment]
![image](https://cloud.githubusercontent.com/assets/10322215/11447173/3640099e-955b-11e5-9a63-a5ad51aa5a3e.png)

Steps to reproduce:
1) Download and open solution from this link (https://www.dropbox.com/s/6d1xjik0a0yw31y/Sa1001BadSpacingOnObjectInit.zip?dl=0)
2) Load missing nuget package /rebuild project
3) Perform cleanup CTRL E,F (silent cleanup)
4) Check extraspace after MyField1 initialization (with StyleCopAnalyzers warning).

**Comment by rros** [comment]
I can confirm this issue. However, as far as I can remember the StyleCop plugin always added spaces in these places. It's just since we started using StyleCop Analyzers in VS2015 that we see the warnings.

I created a screenshot with visible whitespace to demonstrate.
![2015-12-17_110931](https://cloud.githubusercontent.com/assets/279664/11866998/ca1c5d4a-a4ae-11e5-8b7d-0feaab57f7dd.png)
