### ISSUE TITLE
StyleCop crashing Visual Studio with NotSupportedException

### ISSUE THREAD

**Issue by davkean** [StyleCop/StyleCop#259]
Hey, I'm from the Visual Studio reliability team, and StyleCop is crashing Visual Studio on this path:
```
       System.NotSupportedException: 'Specified method is not supported.'
 	KERNELBASE.dll!RaiseException(unsigned long dwExceptionCode, unsigned long dwExceptionFlags, unsigned long nNumberOfArguments, const unsigned long * lpArguments) Line 937	C
 	[Managed to Native Transition]	
>	System.Windows.Forms.dll!System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control caller, System.Delegate method, object[] args, bool synchronous) Line 7846	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Invoke(System.Delegate method, object[] args) Line 7373	C#
 	StyleCop.VisualStudio.dll!StyleCop.VisualStudio.AnalysisHelper.AnalyzeComplete(object sender, System.EventArgs e)	Unknown
 	StyleCop.VisualStudio.dll!StyleCop.VisualStudio.AnalysisThread.AnalyzeProc()	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
 	[Native to Managed Transition]	
 	kernel32.dll!75e96739()	Unknown
 	kernel32.dll![Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown
 	ntdll.dll!__RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 1152	C
 	ntdll.dll!_RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 1069	C

```

Unfortunately, due to the way Windows Forms rethrows the exception, the original stack of the NotSupportedException is being thrown away, but it appears something of inside of [AnalyzeCompleteMain](https://github.com/StyleCop/StyleCop/blob/007dc67059b53cc5a94be676f17ad3ea8881d4ad/Project/Src/StyleCop.VisualStudio/VSIntegration/AnalysisHelper.cs#L485 ) is throwing this exception.

We have no repro, and this is just from crash reports being sent to Microsoft.

We're seen about 1000 hits of this crash across all versions of VS from 16.7 -> 16.9, the past 90 days all against StyleCop.VisualStudio.dll [version: 6.2.7489.1].

**Comment by csdahlberg** [comment]
Thanks for the report.

I tried to repro this on VS 16.8.5 with several different solutions and was unsuccessful. If anyone encounters this and is able to provide a readily-available codebase this can be reproduced with, I'll work on a fix ASAP. I'd also gladly accept a PR.

**Comment by sishik1** [comment]
I have VS2019 16.8.5 and it fails exactly like it was described in the original post. Here is a stack trace:
`Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at StyleCop.VisualStudio.AnalysisHelper.AnalyzeComplete(System.Object, System.EventArgs)
   at StyleCop.VisualStudio.AnalysisThread.AnalyzeProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

Here is what I'm seeing. If StyleCop detects no violations on the file, there is no crash. If there is at least 1 violation, StyleCop displays the number of violations in the error list panel and then VS2019 crash occurs. Here is a sample output of violations, which then triggers VS2019 crash.

`
------ StyleCop 6.2 (build 6.2.7489.1) started ------


------ StyleCop completed ------

========== Violation Count: 6 ==========`

**Comment by davkean** [comment]
@sishik1 Thanks!

1. Can you open another instance of Visual Studio, make sure the Debug -> Exception settings look like this:
![image](https://user-images.githubusercontent.com/1103906/108281981-eb52a700-71d4-11eb-9cab-e1b3ec18d78c.png)
2. Tools -> Attach to Process -> Choose the other devenv instance and make sure it looks like this:

![image](https://user-images.githubusercontent.com/1103906/108282040-06bdb200-71d5-11eb-8428-4be22bb90b42.png)

3. Then repro the situation? 

When it breaks on the original thrown exception, can you Paste the stack and exception message?

**Comment by sishik1** [comment]
I followed the steps to try to capture the stack and exception message, but it looks like it's the same stack trace as above.

**Comment by davkean** [comment]
@sishik1 Can you try again but this time check all the boxes to stop all exceptions and repro the situation? See if that stops earlier.

**Comment by sishik1** [comment]
@davkean This is all I could capture. Hope that this helps:

System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at StyleCop.VisualStudio.AnalysisHelper.AnalyzeComplete(Object sender, EventArgs e)
   at StyleCop.VisualStudio.AnalysisThread.AnalyzeProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

  This exception was originally thrown at this call stack:
    [External Code]

**Comment by csdahlberg** [comment]
Version 6.3.7806.0 of the VS extension has been published with this fix.

**Comment by davkean** [comment]
Thanks @csdahlberg @SanjayGuntur!
