### ISSUE TITLE
CodeClean up always opens all files even no any changes made by cleanup

### ISSUE THREAD

**Issue by dmitriyse** [StyleCop/StyleCop#27]
This issue occurs only if Fix StyleCop violations checked.

Issue reproduced if this option is checked:
![image](https://cloud.githubusercontent.com/assets/10322215/11324955/e4c1f032-9159-11e5-9e01-047318e1eb5e.png)

**Comment by citizenmatt** [comment]
This is ReSharper itself that is opening the files, the StyleCop extension has no influence on this. 

However, what might be happening is that the extension is modifying the file, but setting it to exactly what it already was (e.g. normalising spacing that was already normalised, or applying formatting to a code block that was already formatted). ReSharper might be seeing the modifications, so opening the files, but since the text doesn't actually change, the documents aren't make modified.

Do you have an example where this happens?

**Comment by dmitriyse** [comment]
Hi!
Steps to reproduce:
1) Download and open solution from this link ()
2) Close all files
3) Select solution node in the solution explorer
4) Push CTRL + E,C (CodeCleanup)
5) Check "To enable Undo, open all files with changes for edititng
6) Select "WithoutStyleCop" formatting settings.
![image](https://cloud.githubusercontent.com/assets/10322215/11446962/56a34988-9558-11e5-95b4-f6acae7b748a.png)

7) Push Run and ensure there no any files opened after this operation.

---
8) Select solution node in the solution explorer
9) Push CTRL + E,C (CodeCleanup)
10) Select "WithStyleCop" formatting settings.
11) Push Run and see that assemlyInfo.cs is opened, but no any changes performed by cleanup.
![image](https://cloud.githubusercontent.com/assets/10322215/11446978/79fe6700-9558-11e5-9982-b2ff13cd6343.png)

Those to settings "WithStyleCop" and "WithoutStyleCop" should works equally.
StyleCop reformat force resharper to think that some files was modified or some special state that leads to wrongly opening files.

This problem is critical on a big projects, where you want to control what was reformatted, but 1000+ unchanged files are opened.

**Comment by citizenmatt** [comment]
Looks like it's blindly reapplying the sorted list of `using` statements, so ReSharper opens the "changed" file.
