### ISSUE TITLE
how to prevent generate file header when code cleanup

### ISSUE THREAD

**Issue by chenfeiw** [StyleCop/StyleCop#63]
I am using 'StyleCop by JetBrains 2016.2.0', and enabled 'Fix SytleCop violations' and 'Create XML doc stubs' to generate comments for my class via code cleanup. Every time a file header is added to the file. I tried to disabled SA1633 ~SA1649, but everything is same. 
I also tried enable 'Upldate file header' in code cleanup settings and set an empty 'File header text', it didn't change anything.
How to prevent generation of file header when code cleanup?

**Comment by citizenmatt** [comment]
Ideally, the quick fixes should only do anything if the corresponding rules are enabled. If they're not enabled, I'd not expect them to do anything.

Could you get me a small repro product, please? I can use that to take a look.

**Comment by chenfeiw** [comment]
I created a empty project, and uploaded to GitHub, so I don't know if it is useful for you. But you can see file header is added to the cs file after code cleanup. 
Attachments are screen shots of my ReSharper settings. I'm not sure if there is any incorrect setting. (sorry, I don't know how to export these settings to a file)
![settings1](https://cloud.githubusercontent.com/assets/21239147/18193050/66eafef4-710c-11e6-8826-ac9acb83c99e.PNG)
![settings2](https://cloud.githubusercontent.com/assets/21239147/18193051/66eb593a-710c-11e6-88d2-0e09248c019f.PNG)
![settings3](https://cloud.githubusercontent.com/assets/21239147/18193052/671de42c-710c-11e6-8818-a575bc7f15f2.PNG)

**Comment by chenfeiw** [comment]
this is my code cleanup settings. I just enabled 'Create XML doc stubs'
![cleanup settings2](https://cloud.githubusercontent.com/assets/21239147/18193186/b5a2fe60-710d-11e6-9b04-ad8b5cc89c2d.PNG)
![cleanup settings1](https://cloud.githubusercontent.com/assets/21239147/18193187/b5a5d75c-710d-11e6-9a0b-08c4907e5496.PNG)

**Comment by citizenmatt** [comment]
OK, I think the problem here is that when you set the option in ReSharper to "do not show", you're actually just changing how the violation is displayed, not whether the rule is enabled.

The "truth" for settings is the settings.StyleCop file - to actually disable a rule, you'd need to disable it in the file. This is because StyleCop can also be run from the command line, and if the settings were actually kept in ReSharper, the command line run would have different results.

What would be nicer is if the options page allowed removing the "do not show" option, so it only controlled the severity, and the only way to remove the violation was by the settings.StyleCop file. (But I don't think this will work, as ReSharper also allows hiding the violation with the `// ReSharper disable …` comments).

**Comment by chenfeiw** [comment]
Thanks for your reply. If I only installed the  'StyleCop by JetBrains ' extension, which setting file will be used? I see there are several 'Settings.sSyleCop' under 'appdata\local'.

**Comment by citizenmatt** [comment]
These are default settings files, and shouldn't be modified - the next time the extension is updated, they will be overwritten. You should instead add a settings.stylecop file to your solution, overriding just the settings that you need.

**Comment by chenfeiw** [comment]
Got it. I copied the settings.stylecop file to my solution folder. Thanks again.
