### ISSUE TITLE
StyleCop doesn't work on Visual Studio 15 Preview 5 and ReSharper 2016.2.2

### ISSUE THREAD

**Issue by mlspielt** [StyleCop/StyleCop#71]
I can't get StyleCop to run on Visual Studio Preview 5 and ReSharper 2016.2.2.

StyleCop is installed in the Exstension Manager, but i can't use it anywhere.

**Comment by citizenmatt** [comment]
To be perfectly honest, I'm not currently planning on supporting VS15 right now, mainly because, as a pre-release, it's a moving target for ReSharper.

ReSharper 2016.2.2 doesn't actually support VS15 Preview 5 - I'm a little surprised you got it to install at all! I think you're going to encounter more issues. The just released 2016.3 EAP3 has added support for Preview 5, and we know we're going to be making more changes as the VS preview continues.

But because VS15 support is for 2016.3, that requires a rebuild of the StyleCop plugin, which frankly isn't worth the effort this early in ReSharper's EAP cycle (we're doing stuff to address the need to constantly recompile and retarget plugins for this EAP wave, but it's not there yet).

That said, what problems are you seeing? Does the StyleCop item appear in the options dialog? Is it just a case of missing inspections?

**Comment by dfyx** [comment]
I'm seeing the same problems. It looks as if StyleCop doesn't get loaded at all. I don't see any entries in the options dialog or the context menus and no inspections get run.

**Comment by mvonballmo** [comment]
@citizenmatt: thanks for the detailed answer above. I was just going to ask when we can expect to see support for VS2017 but I have my answer.

For others: VS2017 is in RC1 and R#2016.3EAP9 is the first version that works with it. There are a handful of extensions available, but StyleCop by JetBrains isn't one of them. From what I read above, we'll see a StyleCop extension version when R#2016.3 is final.

**Comment by dmitriyse** [comment]
I managed to get Resharper.StyleCop work in VS 2017 RC
For better compatibility I created two builds one for VS 2015 and VS 2017 RC (
[StyleCop.Resharper.2016.3-eap11.zip](https://github.com/StyleCop/StyleCop/files/632462/StyleCop.Resharper.2016.3-eap11.zip))
Unforunately In EAP 11 all pluging subsystem is broken.
This binaries works with EAP 10.

**Comment by citizenmatt** [comment]
I've just pushed a version that supports ReSharper 2016.3, which is also the only version of ReSharper that officially supports VS2017RC - could you give that a go, please?

Closing for now, please reopen if there are more issues.

**Comment by mvonballmo** [comment]
Works for me in both VS2015 and VS2017RC (with updates from 12. December). Thanks!
