### ISSUE TITLE
StyleCop settings

### ISSUE THREAD

**Issue by andyste1** [StyleCop/StyleCop#74]
Apologies - I know this has been asked before but I'm still unclear on where the settings come from (admittedly I've never got my head around R# layers). I'm using VS2013 with R# 9.2 and the "StyleCop by JetBrains" extension. 

If I go into R# -> Manage Options, I see a list of various layers. Starting from the bottom:
- "Extensions", with a child "StyleCop.StyleCop >> StyleCop"
- "Resharper 8 global settings"
- "This Computer". Editing this, all StyleCop code inspection rules are set to "Warning".
- A child under "This Computer", which is our dev team's ".DotSettings" file. Editing this, I can see a couple of dozen rules that we set to "Do not show" a long time ago. 
- "Solution xxx personal " and "Solution xxx team-shared". Editing these, *all* StyleCop code inspection rules are set to "Warning". 

Here's my first source of confusion (and I realise this is a probably R# thing rather than StyleCop): I thought the upper layers were meant to override the lower layers, but this can't be the case as I would expect to see warnings for *every* StyleCop rule, which doesn't happen. (On a side note, I find the R# UI confusing as it doesn't tell you whether an individual setting is set in that layer, or inherited from a lower layer. Or am I missing something?).

My main issue is that changing a rule in the above .DotSettings file/layer (under "My Computer") seems to have no effect, especially having always assumed this was our "definitive" rule set. In fact, just trying it right now, changing a rule in the top "Solution xxx personal" layer has no effect either. Do I have all this wrong, and is your extension getting its rules from elsewhere? We have a .stylecop settings file in a "root" folder to where all our solutions are located, but changing a rule in here has no effect either.

(For the most part, our editor warning squiggles do match the SAxxxx warnings that we have turned on, so we never had any reason to think there was an issue with how the layers work or where the StyleCop rules are coming from).

**Comment by citizenmatt** [comment]
Layers are very powerful, but also subtle. Three things:

1. Upper layers do override lower layers
2. Values are only written to a layer if it's different to layer(s) below it
3. Editing a layer in isolation shows you what's different between that layer and the hardcoded defaults. It does not include any layers that would normally be lower than it

So, editing the shared solution settings layer means you don't see the "Do not show" settings from your team's .dotSettings file. Changing the values to "Warning" when editing just that layer does nothing, because the hardcoded defaults are "Warning".

Basically, you should always edit with ReSharper &rarr; Options and use the Save To button to write the values to the correct layers. You should now see the team .dotSettings file "Do not show" settings.

If you reset these values and hit save, ReSharper will save to the lowest possible layer, in this case, the team .dotSettings file. It will compare the new value with the layer(s) below, realise that they are the same as the hardcoded defaults and simply remove them from the team .dotSettings file.

If you reset the values and hit Save To and save to the shared team settings layer, ReSharper will want to write there. It will compare with the layer(s) below. It sees a different value in the team .dotSettings file and so writes the new values to the shared team settings layer. If you were trying to set it to "Do not show", it would see that the same value is in the team .dotSettings file and not write anything to the team shared settings layer.

Does that make sense?

As for how this interacts with StyleCop settings, if a rule is disabled in settings.stylecop, then it doesn't get run, even if the ReSharper setting is set to "Warning" or "Error". If the rule is enabled, it gets run, and any squigglies are then evaluated against the ReSharper setting, and shown as a warning or suggestion, or even not shown at all. It's really a way to set the severity of a rule, rather than disable it - StyleCop should be in charge of that.

I'm going to close the issue, feel free to reopen if you need to.
