### ISSUE TITLE
StyleCop Code Cleanup missing in Visual Studio 2015

### ISSUE THREAD

**Issue by jbreuer** [StyleCop/StyleCop#86]
Hello,

I've previously used Visual Studio 2012 with Resharper (9.1.3) and StyleCop (4.7). In the Code Cleanup settings I could choose a lot of StyleCop settings. And if I did a Code Cleanup for a file it would automatically add summaries to classes, methods, etc. 

![vs2012](https://cloud.githubusercontent.com/assets/5444597/23217488/b16c663a-f919-11e6-83d7-9613d85888a5.png)

In Visual Studio 2015 with Resharper (2016.3.2) and StyleCop (tried both 4.7 and 5.0) these options are gone in the Code Cleanup. I also tried to install the StyleCop By JetBrains ReSharper extension.
![vs2015](https://cloud.githubusercontent.com/assets/5444597/23217603/2f87a26e-f91a-11e6-8c3c-395b668bc990.png)

Has this feature been removed in Visual Studio 2015? If yes is there another way I could automatically get the summary above classes, methods, etc if I do a Code Cleanup?

**Comment by citizenmatt** [comment]
It's not related to VS2015, but to the ReSharper extension (StyleCop by JetBrains). And yes, the items have been removed and replaced with just two options - fix violations and create XML documentation stubs.

The idea is to simplify things - instead of having a huge list of settings here, simply fix anything we can. If there is a rule violation, and we can easily fix it, why wouldn't we? If you're not interested in a rule violation, disable the rule in settings.stylecop, rather than have to also disable it in code cleanup. The only exception here is XML documentation creation - while we can automatically add stub values here, if we're ever only creating stubs, is it really worth it? So this is an option, and disabled by default.

**Comment by jbreuer** [comment]
Thank you for your clear explanation! I've enabled the "Create XML docs stubs" and now code cleanup works the same again as it did in VS2012 :-).
